### ISSUE TITLE
Exception in heat_delta_received when handling msg on 'panasonic_aquarea/main/DHW_Heat_Delta

### ISSUE THREAD

**Issue by MEKadan** [kamaradclimber/heishamon-homeassistant#234]
** Versions **

- Home Assistant version (for instance 2023.9): 2024.7.3
- This integration version (for instance 1.1.0): 1.11.0

> [!IMPORTANT]
> It's even better if you can make sure you are using the lastest version for the integration (https://github.com/kamaradclimber/heishamon-homeassistant/releases)

**Describe the bug**

Following error from the log:  
```
Logger: homeassistant.components.mqtt.client
Source: util/logging.py:95
integration: MQTT ([documentation](https://www.home-assistant.io/integrations/mqtt), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+mqtt%22))
First occurred: 29 July 2024 at 19:34:27 (1 occurrences)
Last logged: 29 July 2024 at 19:34:27

Exception in heat_delta_received when handling msg on 'panasonic_aquarea/main/DHW_Heat_Delta': '-7' Traceback (most recent call last): 
File "/config/custom_components/aquarea/water_heater.py", line 156, in heat_delta_received self.update_temperature_bounds() 
File "/config/custom_components/aquarea/water_heater.py", line 117, in update_temperature_bounds self._heat_delta + self._attr_target_temperature
~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```
I'm not sure whether this is from Heishamon, because it is reported by mqqt integration, however, log texts suggest it might have something to do with heishamon. 

**To Reproduce**

Occurs after startup / reboot of the system

**Expected behavior**

No such errors

**Screenshots**

** MQTT dump **

**Comment by MEKadan** [comment]
Thanks! That was quick!
