### ISSUE TITLE
support for firmware update through home assistant

### ISSUE THREAD

**Issue by IgorYbema** [kamaradclimber/heishamon-homeassistant#248]
As the developer of the Heishamon software I would like to discuss the posibility to add upgrading through the home assistant heishamon integration. I am not a python developer and am not a frequent user of home assistant. But I like where it is going and there a lot of users using it.

So what could I do on the heishamon side to support firmware upgrades through this integration?

Currently heishamon firmware updates is done using a POST to the /firmware url with filename and md5 as the post values, including the  firmware itself ofcourse. Is this something which the integration could post a self-downloaded (from github) file to?

I can't make OTA upgrade on heishamon as the ESP8266 is too low on memory to add HTTPS support (required for it to download the binaries from github). I could host the binaries on a HTTP site but that would make it depended on that, probably, single server. That is why I wanted to look into the home assistant method of upgrading the firmware.

**Comment by geduxas** [comment]
HomeAssistant has some powerful tools like Esphome, its portainer based ESP compiler and local OTA update tool.. i think it's possible to use it..

**Comment by geduxas** [comment]
Also, HA is mostly based on docker, and have containers as add-ons, its possible to make some add-on's which task would be update heishamon

**Comment by geduxas** [comment]
And definitely i think it's possible download and simple post into heishamon interface :D

**Comment by kamaradclimber** [comment]
Hey there,
it seems like a really good feature idea.

Two things makes me hesitate though:
- my experience with upgrading heishamon has not been great so far (I tried to upgrade 2 days ago and the upgrade failed silently because the new version has been applied) => the upgrade process would need to send feedback for the integration
- once the integration does the upgrade, it means users will turn to this repo for support when upgrades does not work or brick their device. => heishamon needs to send info to select perfectly the type of binary to download (small or large).

But overall, I would really happy to work in that direction, thanks for the proposal!

**Comment by IgorYbema** [comment]
Good points. Let me think about those things.

**Comment by IgorYbema** [comment]
I have been testing and a basic python code upload that works below.
This already results in a final answer succesful , rebooting or error MD5 wrong or like that.

```
import requests

# Read MD5 hash from a .md5 file
def read_md5(md5_file_path):
    with open(md5_file_path, "r") as f:
        md5_hash = f.read().strip()  # Read the MD5 and strip any extra spaces or newlines
    return md5_hash

# Paths for the firmware file and the .md5 file
file_path = "HeishaMon.ino.d1-v3.8.bin"
md5_file_path = "HeishaMon.ino.d1-v3.8.md5"
url = "http://heishamontest.local/firmware"

# Read MD5 hash from the .md5 file
md5_hash = read_md5(md5_file_path)

# Open the firmware file in binary mode
with open(file_path, 'rb') as firmware_file:
    # Prepare the multipart form-data
    files = {
        'firmware': ('firmware.bin',firmware_file,'application/octet-stream')
    }
    data = {
        'md5': md5_hash
    }

    # Send the POST request
    response = requests.post(url, files=files, data=data)

# Check the response from the server
if response.status_code == 200:
    print("File uploaded successfully!")
    print(response.text)
else:
    print(f"Failed to upload file. Status code: {response.status_code}")
    print(response.text)
```

**Comment by IgorYbema** [comment]
Just tried a v3.0 to v3.8 and it worked fine, right after reboot:
```
Tue Sep 10 16:38:42 2024 (73388): Uploading new firmware: 90%
Tue Sep 10 16:38:42 2024 (74074): Uploading new firmware: 95%
Tue Sep 10 16:38:43 2024 (74782): Readlen: 672640, Totallen: 674627
Tue Sep 10 16:38:43 2024 (74790): Readlen: 673116, Totallen: 674627
Tue Sep 10 16:38:43 2024 (74799): Readlen: 674627, Totallen: 674627
Tue Sep 10 16:38:43 2024 (74802): In /firmware client write part
Tue Sep 10 16:38:43 2024 (74854): Firmware update success
Tue Sep 10 16:38:43 2024 (74863): In /firmware client write part
Tue Sep 10 16:38:43 2024 (74867): In /firmware client write part
```

**Comment by kamaradclimber** [comment]
I flashed to 3.8 with a cable.
Then any attempt to use the script (to downgrade for instance to 3.6) ends up with 
> Remote end closed connection without response

(roughly at the moment we reached 100%).

I've tried to do the upgrade attempt shortly after reboot but no luck so far.

**Comment by geduxas** [comment]
@kamaradclimber do you have correct md5 file? Also does it fit current firmware? If you try to flash firmware without correct md5 it just reboots after upload. Don't remember it will pronounce any error or not...

**Comment by kamaradclimber** [comment]
Yes md5 files are correct and fit the firmware (both for 3.8 and 3.62).
I've tried to remove sending the md5 from the script, no change.

To be clear, the script is not the issue, the firmware upgrade does not work better from the webui.

Should I open a ticket on Egyras/Heishamon repository to summarize the issue so that we can investigate independantly  of this feature? (I think I can implement a draft without having a way to test)

**Comment by geduxas** [comment]
yes indeed, @IgorYbema there is a problem with web stack. If i console web interface i am unable to update firmware. Heishamon will interrupt upload, and closes socket, also i see MQTT reconnect. Next time while trying it will get ~5% of data and does same. After closing web browser and uploading, everything works good.

Console was opened from one device, and python script was run from another. if it makes any sense..

**Comment by IgorYbema** [comment]
Ok I'll try that also. Will be tomorrow.

**Comment by IgorYbema** [comment]
I saw same behaviour indeed. Something to fix :)

**Comment by kamaradclimber** [comment]
It describes exactly what I was facing (looking at the console to follow the update). Thanks for the confirmation.
I’ll retry to update without looking at the console and start the implementation this weekend probably.

**Comment by IgorYbema** [comment]
I believe the websocket implementation is corrupting the memory somewhere. So it mangels some bytes being sent over another webserver connection. I'll take this finding back to my repo and discuss it with Curlymoo.

**Comment by kamaradclimber** [comment]
> heishamon needs to send info to select perfectly the type of binary to download (small or large).

Is there anyway to distinguish the small and large versions of the PCB (with current version of heishamon), something like a mqtt topic that would exist only for one of those models?

In future version of heishamon it would be good to give the info about the type of build the board is running.

**Comment by kamaradclimber** [comment]
I've written https://github.com/kamaradclimber/heishamon-homeassistant/pull/249 as a draft.
- For now it assumes the model is "model-type-small"
- It "works" up to the point the firmware is uploaded (and then heishamon brutally cuts the connection and does not reboot, I don't know how to troubleshoot this).

Any way it's a good start.

If you want to test it easily, you can use the `/developer-tools/action` page on HA that allows to use the `heishamon_firmware.update` action and specify any version.

**Comment by kamaradclimber** [comment]
Would you be able to look at https://github.com/IgorYbema/HeishaMon/pull/140 and tell me if that would be a good idea for Heishamon ?

**Comment by kamaradclimber** [comment]
I've tried to upgrade to 3.9 (from 3.8) on the old PCB model.
Upload works ok, logs:
```
Firmware is 694784 bytes long
Downloaded binary and checksum 5ff24e1f08de3de1aa82e49c2b771b76 of version 3.9
Starting upgrade of firmware to version 3.9 on 192.168.0.80
Currently read 65536 out of 694784: 9%
...
Currently read 694784 out of 694784: 100%
```

but then an error:
```
132420389602496] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2795, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2838, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1006, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1078, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 489, in async_install_with_progress
    await self.async_install(version, backup)
  File "/config/custom_components/aquarea/update.py", line 250, in async_install
    resp = await session.post(
           ^^^^^^^^^^^^^^^^^^^
    ...<8 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client.py", line 730, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1059, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/streams.py", line 671, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
```

which boils down to "the server disconnected" (and does not reboot on new version).

**Comment by kamaradclimber** [comment]
The script posted above works to update. I'll investigate more this weekend.

**Comment by Aida3000** [comment]
The update to the new version has worked for me. Thanks a lot!
